# Generated by Django 5.1.2 on 2024-10-27 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vulnerable_form", "0002_xssprotectedcomment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="xssprotectedcomment",
            name="author",
        ),
    ]
